import React, { useState } from "react";
import { Search, CheckCircle, XCircle, Camera } from "lucide-react";
import { money } from "../lib/utils.js";
import BarcodeDisplay from "./BarcodeDisplay.jsx";
import CameraScanner from "./CameraScanner.jsx";

// Lets staff type, scan with a physical scanner, or scan with the device
// camera to check a slip number against the real sales records.
export default function VerifyView({ sales }) {
  const [query, setQuery] = useState("");
  const [result, setResult] = useState(null);
  const [searched, setSearched] = useState(false);
  const [cameraOpen, setCameraOpen] = useState(false);

  const runCheck = (code) => {
    const match = sales.find((s) => s.invoiceNo === code.trim());
    setResult(match || null);
    setSearched(true);
  };

  const check = () => runCheck(query);

  const handleKeyDown = (e) => {
    if (e.key === "Enter") check();
  };

  const handleCameraScan = (decodedText) => {
    setCameraOpen(false);
    setQuery(decodedText);
    runCheck(decodedText);
  };

  return (
    <div className="pos-single">
      <div className="view-title" style={{ marginBottom: 4 }}>Verify a Bill</div>
      <div className="view-subtitle" style={{ marginBottom: 16 }}>
        Scan the barcode with your camera, use a scanner, or type the Slip number.
      </div>

      <div style={{ display: "flex", gap: 8, marginBottom: 12, flexWrap: "wrap" }}>
        <input
          className="form-input"
          style={{ flex: 1, minWidth: 180 }}
          placeholder="Scan or type Slip # (e.g. 20260825-0001)"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onKeyDown={handleKeyDown}
        />
        <button className="btn-primary" onClick={check}><Search size={15} /> Check</button>
      </div>

      <button
        className="btn-secondary"
        style={{ width: "100%", display: "flex", alignItems: "center", justifyContent: "center", gap: 6, marginBottom: 20 }}
        onClick={() => setCameraOpen(true)}
      >
        <Camera size={16} /> Scan with Camera
      </button>

      {searched && !result && (
        <div className="customer-detail-card" style={{ borderColor: "#AC2B22" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8, color: "#AC2B22", fontWeight: 600 }}>
            <XCircle size={20} /> Not found — this bill does not exist in our records.
          </div>
          <div className="customer-sub" style={{ marginTop: 6 }}>
            This slip number was not generated by this system. Do not accept it as genuine.
          </div>
        </div>
      )}

      {result && (
        <div className="customer-detail-card" style={{ borderColor: "#5C7A56" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8, color: "#5C7A56", fontWeight: 600, marginBottom: 10 }}>
            <CheckCircle size={20} /> Genuine bill — found in records.
          </div>

          <div className="receipt-row"><span>Slip #</span><span>{result.invoiceNo}</span></div>
          <div className="receipt-row"><span>Date</span><span>{result.date}</span></div>
          <div className="receipt-row"><span>Customer</span><span>{result.customerName}</span></div>
          {result.customerPhone && <div className="receipt-row"><span>Phone</span><span>{result.customerPhone}</span></div>}

          <div className="receipt-items" style={{ marginTop: 10 }}>
            {result.items.map((it) => (
              <div key={it.id} className="receipt-row">
                <span>{it.name} ({it.qty} {it.unit})</span>
                <span>{money(it.rate * it.qty)}</span>
              </div>
            ))}
          </div>

          <div className="receipt-row receipt-total"><span>Total</span><span>{money(result.total)}</span></div>

          <div style={{ textAlign: "center", marginTop: 12 }}>
            <BarcodeDisplay value={result.invoiceNo} />
          </div>
        </div>
      )}

      {cameraOpen && (
        <CameraScanner onScan={handleCameraScan} onClose={() => setCameraOpen(false)} />
      )}
    </div>
  );
}